# Generated by Django 4.2.2 on 2023-06-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doc_name',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
    ]
